// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJznG6rGIhibfWxx6Oo_RPg-Pa17YJME',
    appId: '1:1040490728379:web:985585a1744152c629129e',
    messagingSenderId: '1040490728379',
    projectId: 'emai-app-64f02',
    authDomain: 'emai-app-64f02.firebaseapp.com',
    storageBucket: 'emai-app-64f02.firebasestorage.app',
    measurementId: 'G-XHK84RXVE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByjL4hkeEpkaXat0IQFAxeO_KpoWX45Cs',
    appId: '1:1040490728379:android:9ea348ae2d64d37829129e',
    messagingSenderId: '1040490728379',
    projectId: 'emai-app-64f02',
    storageBucket: 'emai-app-64f02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxJBwt4wt1ORwVomJzdfNpGceDd8vQLc',
    appId: '1:1040490728379:ios:0c1c99ef8410d29029129e',
    messagingSenderId: '1040490728379',
    projectId: 'emai-app-64f02',
    storageBucket: 'emai-app-64f02.firebasestorage.app',
    iosBundleId: 'co.carmelitas.emai.emaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSxJBwt4wt1ORwVomJzdfNpGceDd8vQLc',
    appId: '1:1040490728379:ios:0c1c99ef8410d29029129e',
    messagingSenderId: '1040490728379',
    projectId: 'emai-app-64f02',
    storageBucket: 'emai-app-64f02.firebasestorage.app',
    iosBundleId: 'co.carmelitas.emai.emaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdJznG6rGIhibfWxx6Oo_RPg-Pa17YJME',
    appId: '1:1040490728379:web:a140be7c5d55d1dd29129e',
    messagingSenderId: '1040490728379',
    projectId: 'emai-app-64f02',
    authDomain: 'emai-app-64f02.firebaseapp.com',
    storageBucket: 'emai-app-64f02.firebasestorage.app',
    measurementId: 'G-4S18VJ0GV1',
  );
}
