name: emai_app
description: EMAI-APP Demo para reconocimiento de exámenes
publish_to: 'none' # proyecto privado/demo

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #google_ml_kit: 0.16.1
  camera: ^0.10.0
  image_picker: ^0.8.7
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
