name: emai_app
description: EMAI-APP Demo para reconocimiento de exámenes
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Estado / utilidades UI
  provider: ^6.1.2

  # Captura/selección de imagen
  image_picker: ^1.1.2

  # Firebase (núcleo + Firestore) - versiones compatibles entre sí
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.11

  # ML Kit OCR on-device
  google_mlkit_text_recognition: ^0.13.0

  # Opcional
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

